"""
종목 검색 DB — 회사명(한글·영문) → 티커 매핑.
국장 약 450종목 (KOSPI/KOSDAQ 시총 상위)
미장 약 500종목 (S&P 500 전체)
시총 tier(1=최대)로 정렬해 검색 결과 상위에 대형주가 뜬다.
필드: (한글명, 영문명, 티커, tier)
"""
from __future__ import annotations

# ─────────────────────────────────────────────────────────────────────────
# 국장 (KOSPI / KOSDAQ 시총 상위 ~450종목)
# ─────────────────────────────────────────────────────────────────────────
KR_STOCKS: list[tuple[str, str, str, int]] = [
    # ── 반도체·IT ────────────────────────────────────────────
    ("삼성전자", "Samsung Electronics", "005930.KS", 1),
    ("SK하이닉스", "SK Hynix", "000660.KS", 1),
    ("삼성전기", "Samsung Electro-Mechanics", "009150.KS", 2),
    ("삼성SDI", "Samsung SDI", "006400.KS", 2),
    ("LG전자", "LG Electronics", "066570.KS", 2),
    ("한미반도체", "Hanmi Semiconductor", "042700.KS", 2),
    ("DB하이텍", "DB HiTek", "000990.KS", 3),
    ("리노공업", "Leeno Industrial", "058470.KS", 3),
    ("HPSP", "HPSP", "403870.KS", 3),
    ("피에스케이", "PSK", "319660.KS", 3),
    ("원익IPS", "Wonik IPS", "240810.KS", 3),
    ("유진테크", "Eugene Technology", "084370.KQ", 3),
    ("테스", "TES", "095610.KQ", 3),
    ("솔브레인", "Soulbrain", "036830.KQ", 3),
    ("동진쎄미켐", "Dongjin Semichem", "005290.KS", 3),
    ("이오테크닉스", "EO Technics", "039030.KQ", 3),
    ("주성엔지니어링", "Jusung Engineering", "036930.KQ", 3),
    ("하나마이크론", "Hana Microdisplay", "067310.KQ", 3),
    ("심텍", "Simtech", "222800.KQ", 3),
    ("ISC", "ISC", "095340.KQ", 3),
    ("에스앤에스텍", "SNS Tech", "101490.KQ", 3),
    ("코미코", "Komico", "183300.KQ", 3),
    ("인텍플러스", "IntekPlus", "064290.KQ", 3),
    ("삼성SDS", "Samsung SDS", "018260.KS", 2),
    ("SK스퀘어", "SK Square", "402340.KS", 2),
    ("LG이노텍", "LG Innotek", "011070.KS", 2),
    ("현대오토에버", "Hyundai AutoEver", "307950.KS", 2),
    ("두산테스나", "Doosan Tesna", "131970.KQ", 3),
    ("파크시스템스", "Park Systems", "140860.KQ", 3),
    ("씨에스윈드", "CS Wind", "112610.KS", 3),
    ("레이크머티리얼즈", "Lake Materials", "281740.KQ", 3),
    ("티씨케이", "TCK", "064760.KQ", 3),
    ("하이비젼시스템", "Hivision System", "126700.KQ", 3),
    ("켐트로닉스", "Chemtronics", "089010.KQ", 3),
    ("오시텍", "OSITech", "290020.KQ", 3),
    ("에이피티씨", "APTC", "261110.KQ", 3),
    ("기가레인", "GIGA Lane", "049080.KQ", 3),
    ("아이원스", "Iowns", "340930.KQ", 3),
    ("HB솔루션", "HB Solution", "356020.KQ", 3),
    ("퀄리타스반도체", "Qualitas Semiconductor", "432720.KQ", 3),
    # ── 인터넷·플랫폼·게임 ────────────────────────────────
    ("NAVER", "Naver", "035420.KS", 1),
    ("카카오", "Kakao", "035720.KS", 1),
    ("카카오뱅크", "KakaoBank", "323410.KS", 2),
    ("카카오페이", "KakaoPay", "377300.KS", 2),
    ("크래프톤", "Krafton", "259960.KS", 2),
    ("넷마블", "Netmarble", "251270.KS", 2),
    ("엔씨소프트", "NCSoft", "036570.KS", 2),
    ("펄어비스", "Pearl Abyss", "263750.KS", 3),
    ("컴투스", "Com2uS", "078340.KQ", 3),
    ("위메이드", "Wemade", "112040.KQ", 3),
    ("더블유게임즈", "Double U Games", "192080.KQ", 3),
    ("웹젠", "Webzen", "069080.KQ", 3),
    ("게임빌", "Gamevil", "063080.KQ", 3),
    ("플레이웨어즈", "Playwares", "023770.KQ", 3),
    ("에스엠", "SM Entertainment", "041510.KQ", 2),
    ("JYP엔터테인먼트", "JYP Entertainment", "035900.KQ", 2),
    ("와이지엔터테인먼트", "YG Entertainment", "122870.KQ", 2),
    ("하이브", "HYBE", "352820.KS", 2),
    # ── 2차전지·소재·화학 ────────────────────────────────────
    ("LG에너지솔루션", "LG Energy Solution", "373220.KS", 1),
    ("LG화학", "LG Chem", "051910.KS", 1),
    ("포스코퓨처엠", "POSCO Future M", "003670.KS", 2),
    ("에코프로비엠", "EcoPro BM", "247540.KQ", 2),
    ("에코프로", "EcoPro", "086520.KQ", 2),
    ("엘앤에프", "L&F", "066970.KQ", 2),
    ("SKC", "SKC", "011790.KS", 2),
    ("일진머티리얼즈", "Iljin Materials", "020150.KS", 3),
    ("천보", "Chunbo", "278280.KQ", 3),
    ("나노신소재", "Nano New Material", "121600.KQ", 3),
    ("피엔티", "PNT", "137400.KQ", 3),
    ("씨아이에스", "CIS", "222080.KQ", 3),
    ("코스모신소재", "Cosmo Advanced Materials", "005070.KS", 3),
    ("대주전자재료", "Daejoo Electronic Materials", "078600.KQ", 3),
    ("솔루스첨단소재", "Solus Advanced Materials", "336370.KQ", 3),
    ("더블유씨피", "WCP", "393890.KS", 3),
    ("SK아이이테크놀로지", "SK IE Technology", "361610.KS", 2),
    ("롯데케미칼", "Lotte Chemical", "011170.KS", 2),
    ("효성첨단소재", "Hyosung Advanced Materials", "298050.KS", 2),
    ("한화솔루션", "Hanwha Solutions", "009830.KS", 2),
    ("금호석유화학", "Kumho Petrochemical", "011780.KS", 2),
    ("OCI홀딩스", "OCI Holdings", "010060.KS", 2),
    ("SK케미칼", "SK Chemicals", "285130.KS", 2),
    ("KCC", "KCC Corp", "002380.KS", 2),
    ("태광산업", "Taekwang Industrial", "003240.KS", 3),
    ("효성", "Hyosung", "004800.KS", 2),
    ("코오롱인더스트리", "Kolon Industries", "120110.KS", 3),
    ("도레이첨단소재", "Toray Advanced Materials", "도레이.KS", 3),
    ("한국카본", "Korea Carbon", "017960.KS", 3),
    ("태양금속", "Taeyang Metal", "004100.KS", 3),
    # ── 자동차·부품 ────────────────────────────────────────
    ("현대차", "Hyundai Motor", "005380.KS", 1),
    ("기아", "KIA Corp", "000270.KS", 1),
    ("현대모비스", "Hyundai Mobis", "012330.KS", 1),
    ("한온시스템", "Hanon Systems", "018880.KS", 2),
    ("현대위아", "Hyundai WIA", "011210.KS", 2),
    ("HL만도", "HL Mando", "204320.KS", 2),
    ("서연이화", "Seoyeon I-Hwa", "200880.KS", 3),
    ("성우하이텍", "Sungwoo Hitech", "015750.KS", 3),
    ("화신", "Hwashin", "010690.KS", 3),
    ("엠에스오토텍", "MS Autotech", "123040.KQ", 3),
    ("코다코", "Codaco", "046070.KQ", 3),
    ("에스엘", "SL Corporation", "005850.KS", 3),
    ("한국타이어앤테크놀로지", "Hankook Tire & Technology", "161390.KS", 2),
    ("금호타이어", "Kumho Tire", "073240.KS", 2),
    ("넥센타이어", "Nexen Tire", "002350.KS", 2),
    ("만도", "Mando", "009990.KS", 2),
    # ── 금융 ──────────────────────────────────────────────
    ("KB금융", "KB Financial", "105560.KS", 1),
    ("신한지주", "Shinhan Financial", "055550.KS", 1),
    ("하나금융지주", "Hana Financial", "086790.KS", 1),
    ("우리금융지주", "Woori Financial", "316140.KS", 1),
    ("삼성생명", "Samsung Life Insurance", "032830.KS", 1),
    ("삼성화재", "Samsung Fire & Marine", "000810.KS", 2),
    ("메리츠금융지주", "Meritz Financial", "138040.KS", 2),
    ("미래에셋증권", "Mirae Asset Securities", "006800.KS", 2),
    ("한국투자금융지주", "Korea Investment Holdings", "071050.KS", 2),
    ("DB손해보험", "DB Insurance", "005830.KS", 2),
    ("현대해상", "Hyundai Marine & Fire Insurance", "001450.KS", 2),
    ("NH투자증권", "NH Investment & Securities", "005940.KS", 2),
    ("키움증권", "Kiwoom Securities", "039490.KQ", 2),
    ("삼성증권", "Samsung Securities", "016360.KS", 2),
    ("한화생명", "Hanwha Life Insurance", "088350.KS", 2),
    ("교보생명", "Kyobo Life Insurance", "교보.KS", 2),
    ("롯데손해보험", "Lotte Insurance", "000400.KS", 3),
    ("DB금융투자", "DB Financial Investment", "016610.KS", 3),
    ("신한라이프생명보험", "Shinhan Life Insurance", "신한라이프.KS", 3),
    ("대신증권", "Daeshin Securities", "003540.KS", 3),
    ("한국금융지주", "Korea Financial Holdings", "071050.KS", 2),
    ("BNK금융지주", "BNK Financial Group", "138930.KS", 2),
    ("DGB금융지주", "DGB Financial Group", "139130.KS", 2),
    ("JB금융지주", "JB Financial Group", "175330.KS", 2),
    ("하나증권", "Hana Securities", "003450.KS", 3),
    ("SK증권", "SK Securities", "001510.KS", 3),
    ("교보증권", "Kyobo Securities", "030610.KS", 3),
    ("이베스트투자증권", "eBest Investment & Securities", "078020.KQ", 3),
    # ── 필수소비재·식품 ──────────────────────────────────
    ("CJ제일제당", "CJ CheilJedang", "097950.KS", 2),
    ("오리온", "Orion", "271560.KS", 2),
    ("KT&G", "KT&G", "033780.KS", 2),
    ("농심", "Nongshim", "004370.KS", 2),
    ("오뚜기", "Ottogi", "007310.KS", 2),
    ("하이트진로", "Hite Jinro", "000080.KS", 2),
    ("롯데칠성음료", "Lotte Chilsung", "005300.KS", 2),
    ("빙그레", "Binggrae", "005180.KS", 3),
    ("동원F&B", "Dongwon F&B", "049770.KS", 3),
    ("대상", "Daesang", "001680.KS", 3),
    ("삼양식품", "Samyang Foods", "003230.KS", 3),
    ("풀무원", "Pulmuone", "017810.KS", 3),
    ("매일유업", "Maeil Holdings", "267980.KS", 3),
    ("SPC삼립", "SPC Samlip", "005610.KS", 3),
    ("롯데웰푸드", "Lotte Wellfood", "280360.KS", 2),
    ("CJ씨푸드", "CJ Seafood", "011150.KS", 3),
    ("남양유업", "Namyang Dairy", "003475.KS", 3),
    ("동서", "Dongsuh", "026960.KS", 3),
    ("삼양홀딩스", "Samyang Holdings", "000070.KS", 3),
    ("해태제과", "Haitai Confectionery", "해태.KS", 3),
    ("크라운해태홀딩스", "Crown Haitai Holdings", "005740.KS", 3),
    # ── 바이오·헬스케어 ──────────────────────────────────
    ("삼성바이오로직스", "Samsung Biologics", "207940.KS", 1),
    ("셀트리온", "Celltrion", "068270.KS", 1),
    ("셀트리온헬스케어", "Celltrion Healthcare", "091990.KS", 2),
    ("유한양행", "Yuhan Corp", "000100.KS", 2),
    ("한미약품", "Hanmi Pharm", "128940.KS", 2),
    ("종근당", "Chong Kun Dang", "185750.KS", 2),
    ("대웅제약", "Daewoong Pharma", "069620.KS", 2),
    ("동아에스티", "Dong-A ST", "170900.KS", 3),
    ("휴젤", "Hugel", "145020.KQ", 2),
    ("클래시스", "Classys", "214150.KQ", 3),
    ("보령", "Boryung", "003850.KS", 3),
    ("광동제약", "Kwangdong Pharma", "009290.KS", 3),
    ("일동제약", "Ildong Pharma", "249420.KS", 3),
    ("동화약품", "Dong-wha Pharma", "000020.KS", 3),
    ("에스티팜", "ST Pharm", "237690.KQ", 3),
    ("알테오젠", "Alteogen", "196170.KQ", 2),
    ("유바이오로직스", "EuBiologics", "206650.KQ", 3),
    ("씨젠", "Seegene", "096530.KQ", 2),
    ("피씨엘", "PCL", "241820.KQ", 3),
    ("HLB", "HLB", "028300.KQ", 2),
    ("HLB생명과학", "HLB Life Science", "067630.KQ", 3),
    ("레고켐바이오", "Legochem Biosciences", "141080.KQ", 3),
    ("코오롱티슈진", "Kolon TissueGene", "950160.KQ", 3),
    ("제넥신", "Genexine", "095700.KQ", 3),
    ("메디톡스", "Medytox", "086900.KQ", 3),
    ("오스코텍", "Oscotec", "039200.KQ", 3),
    ("녹십자홀딩스", "GC Holdings", "005450.KS", 2),
    ("녹십자", "Green Cross", "006280.KS", 2),
    ("JW중외제약", "JW Pharma", "001060.KS", 3),
    ("한독", "Handok", "002390.KS", 3),
    ("신풍제약", "Shin Poong Pharma", "019170.KS", 3),
    ("대원제약", "Daewon Pharma", "003220.KS", 3),
    ("한올바이오파마", "Hanall Biopharma", "009420.KS", 3),
    ("바이넥스", "Binex", "053030.KQ", 3),
    ("차바이오텍", "CHA Biotech", "085660.KQ", 3),
    ("메디포스트", "Medipost", "078160.KQ", 3),
    ("티움바이오", "Tium Bio", "321550.KQ", 3),
    # ── 지주·소재·철강 ────────────────────────────────────
    ("POSCO홀딩스", "POSCO Holdings", "005490.KS", 1),
    ("LG", "LG Corp", "003550.KS", 1),
    ("SK", "SK Inc", "034730.KS", 1),
    ("고려아연", "Korea Zinc", "010130.KS", 2),
    ("현대제철", "Hyundai Steel", "004020.KS", 2),
    ("동국제강", "Dongkuk Steel", "001230.KS", 3),
    ("세아베스틸지주", "SeAH Besteel Holdings", "001430.KS", 3),
    ("동일철강", "Dongil Steel", "025560.KS", 3),
    ("한국철강", "Korea Steel", "104700.KS", 3),
    ("삼성물산", "Samsung C&T", "028260.KS", 1),
    ("CJ", "CJ Corp", "001040.KS", 2),
    ("롯데지주", "Lotte Corp", "004990.KS", 2),
    ("한화", "Hanwha Corp", "000880.KS", 2),
    ("GS", "GS Holdings", "078930.KS", 2),
    ("두산", "Doosan", "000150.KS", 2),
    ("LS", "LS Corp", "006260.KS", 2),
    ("현대중공업지주", "HD Hyundai", "267250.KS", 2),
    ("영풍", "Young Poong", "000670.KS", 3),
    ("고려개발", "Korea Development", "003390.KS", 3),
    # ── 통신 ──────────────────────────────────────────────
    ("SK텔레콤", "SK Telecom", "017670.KS", 1),
    ("KT", "KT Corp", "030200.KS", 1),
    ("LG유플러스", "LG Uplus", "032640.KS", 2),
    ("SKB", "SK Broadband", "SKB.KS", 3),
    # ── 건설·부동산 ───────────────────────────────────────
    ("현대건설", "Hyundai E&C", "000720.KS", 2),
    ("GS건설", "GS Engineering", "006360.KS", 2),
    ("DL이앤씨", "DL E&C", "375500.KS", 2),
    ("대우건설", "Daewoo E&C", "047040.KS", 2),
    ("포스코이앤씨", "POSCO E&C", "047050.KS", 2),
    ("HDC현대산업개발", "HDC Hyundai Development", "294870.KS", 2),
    ("롯데건설", "Lotte Engineering", "007850.KS", 3),
    ("태영건설", "Taeyoung E&C", "009410.KS", 3),
    ("HL D&I한라", "HL D&I Halla", "014790.KS", 3),
    ("금호건설", "Kumho E&C", "002990.KS", 3),
    ("계룡건설산업", "Gyeryong Construction", "013580.KS", 3),
    ("한신공영", "Hansin Engineering", "004960.KS", 3),
    # ── 유통·소비재·서비스 ───────────────────────────────
    ("롯데쇼핑", "Lotte Shopping", "023530.KS", 2),
    ("이마트", "E-Mart", "139480.KS", 2),
    ("BGF리테일", "BGF Retail", "282330.KS", 2),
    ("CJ ENM", "CJ ENM", "035760.KS", 2),
    ("호텔신라", "Hotel Shilla", "008770.KS", 2),
    ("신세계", "Shinsegae", "004170.KS", 2),
    ("GS리테일", "GS Retail", "007070.KS", 2),
    ("현대백화점", "Hyundai Department Store", "069960.KS", 2),
    ("롯데하이마트", "Lotte Himart", "071840.KS", 3),
    ("GS홈쇼핑", "GS Home Shopping", "028150.KS", 3),
    ("CJ올리브영", "CJ Olive Young", "CJ올리브.KS", 2),
    ("쿠팡", "Coupang", "CPNG", 1),
    ("카카오커머스", "Kakao Commerce", "카카오커머스.KS", 2),
    ("신세계인터내셔날", "Shinsegae International", "031430.KS", 3),
    ("현대홈쇼핑", "Hyundai Home Shopping", "057050.KS", 3),
    ("롯데백화점", "Lotte Department Store", "롯데백화점.KS", 3),
    # ── 에너지·유틸리티 ──────────────────────────────────
    ("한국전력", "KEPCO", "015760.KS", 1),
    ("두산에너빌리티", "Doosan Enerbility", "034020.KS", 2),
    ("한국가스공사", "KOGAS", "036460.KS", 2),
    ("S-OIL", "S-Oil", "010950.KS", 2),
    ("SK이노베이션", "SK Innovation", "096770.KS", 2),
    ("GS에너지", "GS Energy", "078150.KS", 2),
    ("한국석유공사", "KNOC", "한국석유.KS", 3),
    ("한전KPS", "KEPCO KPS", "051600.KS", 3),
    ("한전기술", "KEPCO Engineering", "052690.KS", 3),
    # ── 조선·기계·방산 ────────────────────────────────────
    ("HD한국조선해양", "HD KSOE", "009540.KS", 1),
    ("삼성중공업", "Samsung Heavy Industries", "010140.KS", 2),
    ("한화오션", "Hanwha Ocean", "042660.KS", 2),
    ("HD현대중공업", "HD Hyundai Heavy Industries", "329180.KS", 2),
    ("HD현대마린솔루션", "HD Hyundai Marine Solution", "443060.KS", 2),
    ("한화에어로스페이스", "Hanwha Aerospace", "012450.KS", 1),
    ("LIG넥스원", "LIG Nex1", "079550.KS", 2),
    ("한국항공우주", "Korea Aerospace Industries", "047810.KS", 2),
    ("현대로템", "Hyundai Rotem", "064350.KS", 2),
    ("HSD엔진", "HSD Engine", "082740.KS", 3),
    ("현대미포조선", "Hyundai Mipo Dockyard", "010620.KS", 2),
    ("성광벤드", "Sungkwang Bend", "014620.KS", 3),
    # ── 항공·운수·물류 ────────────────────────────────────
    ("대한항공", "Korean Air", "003490.KS", 2),
    ("아시아나항공", "Asiana Airlines", "020560.KS", 2),
    ("HMM", "HMM", "011200.KS", 2),
    ("현대글로비스", "Hyundai Glovis", "086280.KS", 2),
    ("CJ대한통운", "CJ Logistics", "000120.KS", 2),
    ("한진", "Hanjin", "002320.KS", 3),
    ("팬오션", "Pan Ocean", "028670.KS", 3),
    ("KSS해운", "KSS Line", "009730.KS", 3),
    ("대한해운", "Korea Line", "005880.KS", 3),
    ("에어부산", "Air Busan", "298690.KS", 3),
    ("제주항공", "Jeju Air", "089590.KQ", 3),
    # ── 미디어·엔터테인먼트 ──────────────────────────────
    ("카카오엔터테인먼트", "Kakao Entertainment", "카카오엔터.KS", 2),
    ("에스엠", "SM Entertainment", "041510.KQ", 2),
    ("JYP엔터테인먼트", "JYP Entertainment", "035900.KQ", 2),
    ("와이지엔터테인먼트", "YG Entertainment", "122870.KQ", 2),
    ("하이브", "HYBE", "352820.KS", 2),
    ("콘텐트리중앙", "Contenree JoongAng", "036420.KS", 3),
    ("스튜디오드래곤", "Studio Dragon", "253450.KQ", 3),
    ("NEW", "Next Entertainment World", "160550.KQ", 3),
    # ── 교육 ─────────────────────────────────────────────
    ("메가스터디교육", "Megastudy Education", "215200.KQ", 3),
    ("에스티씨랩", "STC Lab", "에스티씨.KQ", 3),
    ("웅진씽크빅", "Woongjin ThinkBig", "095720.KQ", 3),
    # ── 의료기기·장비 ─────────────────────────────────────
    ("오스템임플란트", "Osstem Implant", "048260.KQ", 2),
    ("덴티움", "Dentium", "145720.KQ", 3),
    ("인바디", "InBody", "041830.KQ", 3),
    ("뷰노", "Vuno", "338220.KQ", 3),
    ("루닛", "Lunit", "328130.KQ", 3),
    ("제이엘케이", "JLK", "322510.KQ", 3),
    ("SK바이오사이언스", "SK Bioscience", "302440.KS", 2),
    ("SK바이오팜", "SK Biopharmaceuticals", "326030.KS", 2),
]

# ─────────────────────────────────────────────────────────────────────────
# 미장 — S&P 500 전체 + 주요 나스닥
# ─────────────────────────────────────────────────────────────────────────
US_STOCKS: list[tuple[str, str, str, int]] = [
    # ── 정보기술 ──────────────────────────────────────────
    ("애플", "Apple", "AAPL", 1),
    ("마이크로소프트", "Microsoft", "MSFT", 1),
    ("엔비디아", "NVIDIA", "NVDA", 1),
    ("브로드컴", "Broadcom", "AVGO", 1),
    ("오라클", "Oracle", "ORCL", 1),
    ("어도비", "Adobe", "ADBE", 1),
    ("세일즈포스", "Salesforce", "CRM", 1),
    ("AMD", "AMD", "AMD", 1),
    ("퀄컴", "Qualcomm", "QCOM", 1),
    ("텍사스인스트루먼트", "Texas Instruments", "TXN", 1),
    ("인튜이트", "Intuit", "INTU", 1),
    ("인텔", "Intel", "INTC", 1),
    ("어플라이드머티리얼즈", "Applied Materials", "AMAT", 1),
    ("마이크론", "Micron Technology", "MU", 1),
    ("ASML", "ASML", "ASML", 1),
    ("서비스나우", "ServiceNow", "NOW", 1),
    ("팔로알토네트웍스", "Palo Alto Networks", "PANW", 1),
    ("시놉시스", "Synopsys", "SNPS", 1),
    ("케이던스", "Cadence Design", "CDNS", 1),
    ("암페놀", "Amphenol", "APH", 1),
    ("TE커넥티비티", "TE Connectivity", "TEL", 2),
    ("포티넷", "Fortinet", "FTNT", 2),
    ("기스크", "Keysight Technologies", "KEYS", 2),
    ("ANSYS", "ANSYS", "ANSS", 2),
    ("모놀리식파워", "Monolithic Power Systems", "MPWR", 2),
    ("엔페이즈에너지", "Enphase Energy", "ENPH", 2),
    ("코닝", "Corning", "GLW", 2),
    ("아카마이", "Akamai Technologies", "AKAM", 2),
    ("F5네트웍스", "F5 Networks", "FFIV", 2),
    ("주니퍼네트웍스", "Juniper Networks", "JNPR", 2),
    ("시게이트", "Seagate Technology", "STX", 2),
    ("웨스턴디지털", "Western Digital", "WDC", 2),
    ("넷앱", "NetApp", "NTAP", 2),
    ("TSMC", "TSMC", "TSM", 1),
    ("레이시온", "RTX Corp", "RTX", 1),
    ("클라우드플레어", "Cloudflare", "NET", 2),
    ("스노우플레이크", "Snowflake", "SNOW", 2),
    ("팔란티어", "Palantir", "PLTR", 2),
    ("코인베이스", "Coinbase", "COIN", 2),
    ("줌", "Zoom Video", "ZM", 2),
    ("데이터독", "Datadog", "DDOG", 2),
    ("몽고DB", "MongoDB", "MDB", 2),
    ("오토데스크", "Autodesk", "ADSK", 2),
    ("아리스타네트웍스", "Arista Networks", "ANET", 1),
    ("버텍스", "Vertex Inc", "VERX", 3),
    ("스플렁크", "Splunk", "SPLK", 2),
    ("지스케일러", "Zscaler", "ZS", 2),
    ("오크타", "Okta", "OKTA", 2),
    ("트위리오", "Twilio", "TWLO", 2),
    ("워크데이", "Workday", "WDAY", 2),
    ("도큐사인", "DocuSign", "DOCU", 2),
    ("박스", "Box", "BOX", 3),
    ("드롭박스", "Dropbox", "DBX", 3),
    ("퀄트릭스", "Qualtrics", "XM", 3),
    ("DXC테크놀로지", "DXC Technology", "DXC", 3),
    ("HP", "HP Inc", "HPQ", 2),
    ("HPE", "Hewlett Packard Enterprise", "HPE", 2),
    ("IBM", "IBM", "IBM", 1),
    ("액센추어", "Accenture", "ACN", 1),
    ("가트너", "Gartner", "IT", 2),
    ("EPAM시스템", "EPAM Systems", "EPAM", 2),
    ("플렉스", "Flex", "FLEX", 2),
    ("하니웰", "Honeywell", "HON", 1),
    ("래티스반도체", "Lattice Semiconductor", "LSCC", 3),
    ("마벨테크놀로지", "Marvell Technology", "MRVL", 1),
    ("KLA", "KLA Corp", "KLAC", 1),
    ("램리서치", "Lam Research", "LRCX", 1),
    # ── 커뮤니케이션서비스 ────────────────────────────────
    ("알파벳·구글", "Alphabet Google", "GOOGL", 1),
    ("메타", "Meta Platforms", "META", 1),
    ("넷플릭스", "Netflix", "NFLX", 1),
    ("월트디즈니", "Walt Disney", "DIS", 1),
    ("컴캐스트", "Comcast", "CMCSA", 1),
    ("버라이즌", "Verizon", "VZ", 1),
    ("AT&T", "AT&T", "T", 1),
    ("T모바일", "T-Mobile", "TMUS", 1),
    ("차터커뮤니케이션", "Charter Communications", "CHTR", 1),
    ("테이크투인터랙티브", "Take-Two Interactive", "TTWO", 2),
    ("EA스포츠", "Electronic Arts", "EA", 2),
    ("매치그룹", "Match Group", "MTCH", 2),
    ("라이브네이션", "Live Nation", "LYV", 2),
    ("인터퍼블릭", "Interpublic Group", "IPG", 2),
    ("옴니컴", "Omnicom Group", "OMC", 2),
    ("뉴스코프", "News Corp", "NWS", 2),
    ("폭스코프", "Fox Corp", "FOXA", 2),
    ("워너브라더스", "Warner Bros Discovery", "WBD", 2),
    ("파라마운트", "Paramount Global", "PARA", 2),
    ("스포티파이", "Spotify", "SPOT", 2),
    ("핀터레스트", "Pinterest", "PINS", 2),
    ("스냅", "Snap", "SNAP", 2),
    ("트위터엑스", "X Corp Twitter", "X", 2),
    ("레딧", "Reddit", "RDDT", 2),
    # ── 경기소비재 ────────────────────────────────────────
    ("아마존", "Amazon", "AMZN", 1),
    ("테슬라", "Tesla", "TSLA", 1),
    ("홈디포", "Home Depot", "HD", 1),
    ("맥도날드", "McDonald's", "MCD", 1),
    ("나이키", "Nike", "NKE", 1),
    ("로우스", "Lowe's", "LOW", 1),
    ("스타벅스", "Starbucks", "SBUX", 1),
    ("타겟", "Target", "TGT", 1),
    ("TJX컴퍼니", "TJX Companies", "TJX", 1),
    ("부킹홀딩스", "Booking Holdings", "BKNG", 1),
    ("에어비앤비", "Airbnb", "ABNB", 1),
    ("치폴레", "Chipotle Mexican Grill", "CMG", 1),
    ("메리어트", "Marriott International", "MAR", 1),
    ("힐튼", "Hilton Worldwide", "HLT", 1),
    ("얌브랜즈", "Yum! Brands", "YUM", 2),
    ("달러제너럴", "Dollar General", "DG", 2),
    ("달러트리", "Dollar Tree", "DLTR", 2),
    ("로스스토어", "Ross Stores", "ROST", 2),
    ("오토존", "AutoZone", "AZO", 2),
    ("오릴리오토모티브", "O'Reilly Automotive", "ORLY", 2),
    ("어드밴스오토파츠", "Advance Auto Parts", "AAP", 3),
    ("캐맥스", "CarMax", "KMX", 2),
    ("풀코프", "Pool Corp", "POOL", 2),
    ("펄트홈", "PulteGroup", "PHM", 2),
    ("톨브라더스", "Toll Brothers", "TOL", 2),
    ("NVR", "NVR Inc", "NVR", 2),
    ("레나", "Lennar", "LEN", 2),
    ("DR호튼", "D.R. Horton", "DHI", 2),
    ("모호크인더스트리", "Mohawk Industries", "MHK", 3),
    ("PVH코프", "PVH Corp", "PVH", 3),
    ("랄프로렌", "Ralph Lauren", "RL", 2),
    ("가민", "Garmin", "GRMN", 2),
    ("압텍", "Aptiv", "APTV", 2),
    ("보르그워너", "BorgWarner", "BWA", 2),
    ("포드", "Ford Motor", "F", 1),
    ("제너럴모터스", "General Motors", "GM", 1),
    ("리비안", "Rivian", "RIVN", 2),
    ("루시드", "Lucid Group", "LCID", 2),
    ("우버", "Uber Technologies", "UBER", 1),
    ("리프트", "Lyft", "LYFT", 2),
    ("엑스페디아", "Expedia Group", "EXPE", 2),
    ("에어비앤비", "Airbnb", "ABNB", 1),
    ("로얄캐리비안", "Royal Caribbean", "RCL", 2),
    ("카니발", "Carnival Corp", "CCL", 2),
    ("노르웨이지안크루즈", "Norwegian Cruise Line", "NCLH", 3),
    ("MGM리조트", "MGM Resorts", "MGM", 2),
    ("라스베이거스샌즈", "Las Vegas Sands", "LVS", 2),
    ("윈리조트", "Wynn Resorts", "WYNN", 2),
    ("DraftKings", "DraftKings", "DKNG", 2),
    ("넥스타미디어", "Nexstar Media", "NXST", 3),
    ("레스토랑브랜드", "Restaurant Brands", "QSR", 2),
    ("도미노피자", "Domino's Pizza", "DPZ", 2),
    ("얌차이나", "Yum China", "YUMC", 2),
    ("더치브로스", "Dutch Bros", "BROS", 3),
    # ── 필수소비재 ────────────────────────────────────────
    ("코카콜라", "Coca-Cola", "KO", 1),
    ("펩시코", "PepsiCo", "PEP", 1),
    ("P&G", "Procter & Gamble", "PG", 1),
    ("코스트코", "Costco", "COST", 1),
    ("월마트", "Walmart", "WMT", 1),
    ("필립모리스", "Philip Morris International", "PM", 1),
    ("알트리아", "Altria Group", "MO", 1),
    ("에스티로더", "Estee Lauder", "EL", 2),
    ("콜게이트", "Colgate-Palmolive", "CL", 2),
    ("킴벌리클라크", "Kimberly-Clark", "KMB", 2),
    ("제너럴밀스", "General Mills", "GIS", 2),
    ("켈라노바", "Kellanova", "K", 2),
    ("몬델리즈", "Mondelez International", "MDLZ", 1),
    ("허쉬", "Hershey", "HSY", 2),
    ("처치앤드와이트", "Church & Dwight", "CHD", 2),
    ("크로거", "Kroger", "KR", 2),
    ("시스코", "Sysco Corp", "SYY", 2),
    ("US푸즈", "US Foods", "USFD", 3),
    ("암트로직", "BJ's Wholesale Club", "BJ", 3),
    ("달러제너럴", "Dollar General", "DG", 2),
    ("스프라우트파머스마켓", "Sprouts Farmers Market", "SFM", 3),
    ("콘아그라", "Conagra Brands", "CAG", 2),
    ("맥코믹", "McCormick & Co", "MKC", 2),
    ("호멜", "Hormel Foods", "HRL", 2),
    ("JM스머커", "JM Smucker", "SJM", 2),
    ("캠벨수프", "Campbell Soup", "CPB", 2),
    ("클로록스", "Clorox", "CLX", 2),
    ("에너자이저", "Energizer Holdings", "ENR", 3),
    ("레킷벤키저", "Reckitt Benckiser", "RBGLY", 3),
    ("입소스", "BG Group", "BG", 3),
    ("ADM", "Archer-Daniels-Midland", "ADM", 2),
    ("번지글로벌", "Bunge Global", "BG", 2),
    ("모자이크", "Mosaic Company", "MOS", 2),
    ("CF인더스트리", "CF Industries", "CF", 2),
    ("FMC코프", "FMC Corp", "FMC", 2),
    # ── 헬스케어 ──────────────────────────────────────────
    ("일라이릴리", "Eli Lilly", "LLY", 1),
    ("유나이티드헬스", "UnitedHealth Group", "UNH", 1),
    ("존슨앤존슨", "Johnson & Johnson", "JNJ", 1),
    ("애브비", "AbbVie", "ABBV", 1),
    ("머크", "Merck & Co", "MRK", 1),
    ("써모피셔", "Thermo Fisher Scientific", "TMO", 1),
    ("애보트", "Abbott Laboratories", "ABT", 1),
    ("다나허", "Danaher", "DHR", 1),
    ("인튜이티브서지컬", "Intuitive Surgical", "ISRG", 1),
    ("엘레반스헬스", "Elevance Health", "ELV", 1),
    ("CVS헬스", "CVS Health", "CVS", 1),
    ("메드트로닉", "Medtronic", "MDT", 1),
    ("암젠", "Amgen", "AMGN", 1),
    ("길리어드", "Gilead Sciences", "GILD", 1),
    ("리제네론", "Regeneron Pharmaceuticals", "REGN", 1),
    ("버텍스파마", "Vertex Pharmaceuticals", "VRTX", 1),
    ("조에티스", "Zoetis", "ZTS", 1),
    ("스트라이커", "Stryker", "SYK", 1),
    ("보스턴사이언티픽", "Boston Scientific", "BSX", 1),
    ("에드워즈라이프사이언", "Edwards Lifesciences", "EW", 1),
    ("백스터", "Baxter International", "BAX", 2),
    ("BD", "Becton Dickinson", "BDX", 1),
    ("아이큐비아", "IQVIA Holdings", "IQV", 2),
    ("시그나", "Cigna", "CI", 1),
    ("HCA헬스케어", "HCA Healthcare", "HCA", 1),
    ("맥케슨", "McKesson Corp", "MCK", 1),
    ("아메리소스버겐", "AmerisourceBergen", "ABC", 1),
    ("카디널헬스", "Cardinal Health", "CAH", 2),
    ("화이자", "Pfizer", "PFE", 1),
    ("바이오젠", "Biogen", "BIIB", 1),
    ("모더나", "Moderna", "MRNA", 1),
    ("아스트라제네카", "AstraZeneca", "AZN", 1),
    ("노보노디스크", "Novo Nordisk", "NVO", 1),
    ("험뉴헬스케어", "Humana", "HUM", 1),
    ("센텐", "Centene Corp", "CNC", 1),
    ("몰리나", "Molina Healthcare", "MOH", 2),
    ("다빗", "DaVita", "DVA", 2),
    ("IDEXX", "IDEXX Laboratories", "IDXX", 2),
    ("덱스컴", "DexCom", "DXCM", 2),
    ("알컨", "Alcon", "ALC", 2),
    ("힝크스턴스", "Hologic", "HOLX", 2),
    ("인슐렛", "Insulet Corp", "PODD", 2),
    ("헨리샤인", "Henry Schein", "HSIC", 3),
    ("비아트리스", "Viatris", "VTRS", 3),
    ("바이오테크네", "Bio-Techne", "TECH", 3),
    ("워터스", "Waters Corp", "WAT", 2),
    ("매틀러톨레도", "Mettler-Toledo", "MTD", 2),
    ("레스메드", "ResMed", "RMD", 2),
    ("익스펙트럼파마", "Spectrum Pharmaceuticals", "SPPI", 3),
    ("앨러건에스테틱스", "Allergan", "AGN", 2),
    ("에클립스제약", "Agilent Technologies", "A", 2),
    ("PerkinElmer", "PerkinElmer", "PKI", 2),
    ("인테그라라이프사이언", "Integra LifeSciences", "IART", 3),
    ("코퍼레이티드", "CONMED Corp", "CNMD", 3),
    ("오르토피딕", "Ortho Clinical Diagnostics", "OCDX", 3),
    ("패스트마켓", "Invacare", "IVC", 3),
    ("커티스라이트", "Curtiss-Wright", "CW", 3),
    ("인사이트", "Incyte Corp", "INCY", 2),
    ("세엘진", "Celgene", "CELG", 2),
    ("블루버드바이오", "Bluebird Bio", "BLUE", 3),
    ("알렉시온", "Alexion Pharmaceuticals", "ALXN", 2),
    ("BioMarin", "BioMarin Pharmaceutical", "BMRN", 2),
    ("이오반스", "Iovance Biotherapeutics", "IOVA", 3),
    ("카이트파마", "Kite Pharma", "KITE", 3),
    ("울트라제닉스", "Ultragenyx", "RARE", 3),
    ("넥타테라퓨틱스", "Nektar Therapeutics", "NKTR", 3),
    # ── 금융 ──────────────────────────────────────────────
    ("버크셔해서웨이", "Berkshire Hathaway", "BRK-B", 1),
    ("JP모건", "JPMorgan Chase", "JPM", 1),
    ("비자", "Visa", "V", 1),
    ("마스터카드", "Mastercard", "MA", 1),
    ("뱅크오브아메리카", "Bank of America", "BAC", 1),
    ("웰스파고", "Wells Fargo", "WFC", 1),
    ("골드만삭스", "Goldman Sachs", "GS", 1),
    ("모건스탠리", "Morgan Stanley", "MS", 1),
    ("블랙록", "BlackRock", "BLK", 1),
    ("씨티그룹", "Citigroup", "C", 1),
    ("CB인슈어런스", "Chubb Limited", "CB", 1),
    ("마쉬앤맥레넌", "Marsh & McLennan", "MMC", 1),
    ("에이온", "Aon plc", "AON", 1),
    ("메트라이프", "MetLife", "MET", 1),
    ("프루덴셜", "Prudential Financial", "PRU", 1),
    ("아플락", "Aflac", "AFL", 1),
    ("AIG", "American International Group", "AIG", 1),
    ("하트포드파이낸셜", "Hartford Financial", "HIG", 1),
    ("트래블러스", "Travelers Companies", "TRV", 1),
    ("올스테이트", "Allstate", "ALL", 1),
    ("프로그레시브", "Progressive Corp", "PGR", 1),
    ("신시내티파이낸셜", "Cincinnati Financial", "CINF", 2),
    ("유넘그룹", "Unum Group", "UNM", 2),
    ("글로브라이프", "Globe Life", "GL", 2),
    ("아치캐피탈", "Arch Capital", "ACGL", 2),
    ("에버레스트리", "Everest Re", "RE", 2),
    ("RNR리", "RenaissanceRe", "RNR", 2),
    ("무디스", "Moody's", "MCO", 1),
    ("S&P글로벌", "S&P Global", "SPGI", 1),
    ("MSCI", "MSCI Inc", "MSCI", 1),
    ("인터컨티넨탈익스체인지", "Intercontinental Exchange", "ICE", 1),
    ("CME그룹", "CME Group", "CME", 1),
    ("나스닥", "Nasdaq Inc", "NDAQ", 1),
    ("팩츠셋리서치", "FactSet Research", "FDS", 2),
    ("프랭클린리소스", "Franklin Resources", "BEN", 2),
    ("인베스코", "Invesco", "IVZ", 2),
    ("아메리칸익스프레스", "American Express", "AXP", 1),
    ("블랙스톤", "Blackstone", "BX", 1),
    ("아폴로글로벌", "Apollo Global Management", "APO", 1),
    ("KKR", "KKR & Co", "KKR", 1),
    ("칼라일그룹", "Carlyle Group", "CG", 2),
    ("에어리스매니지먼트", "Ares Management", "ARES", 1),
    ("브룩필드애셋", "Brookfield Asset Management", "BAM", 1),
    ("T로웨프라이스", "T. Rowe Price", "TROW", 2),
    ("피프스서드뱅코프", "Fifth Third Bancorp", "FITB", 2),
    ("리전스파이낸셜", "Regions Financial", "RF", 2),
    ("헌팅턴뱅셰어", "Huntington Bancshares", "HBAN", 2),
    ("키코프", "KeyCorp", "KEY", 2),
    ("지온즈뱅코프", "Zions Bancorporation", "ZION", 2),
    ("컴패스뱅크", "Comerica", "CMA", 2),
    ("US뱅코프", "U.S. Bancorp", "USB", 1),
    ("PNC파이낸셜", "PNC Financial Services", "PNC", 1),
    ("캐피탈원", "Capital One Financial", "COF", 1),
    ("동기은행", "Synchrony Financial", "SYF", 2),
    ("얼라이파이낸셜", "Ally Financial", "ALLY", 2),
    ("시티즌스파이낸셜", "Citizens Financial", "CFG", 2),
    ("실버게이트캐피탈", "SVB Financial", "SIVB", 2),
    ("웨스트퍼시픽", "Western Alliance Bancorporation", "WAL", 2),
    ("사이악스파이낸셜", "Synovus Financial", "SNV", 2),
    # ── 산업재 ────────────────────────────────────────────
    ("유니온퍼시픽", "Union Pacific", "UNP", 1),
    ("캐터필러", "Caterpillar", "CAT", 1),
    ("GE에어로스페이스", "GE Aerospace", "GE", 1),
    ("록히드마틴", "Lockheed Martin", "LMT", 1),
    ("보잉", "Boeing", "BA", 1),
    ("허니웰", "Honeywell", "HON", 1),
    ("이튼", "Eaton Corp", "ETN", 1),
    ("에머슨일렉트릭", "Emerson Electric", "EMR", 1),
    ("일리노이툴웍스", "Illinois Tool Works", "ITW", 1),
    ("파커하니핀", "Parker Hannifin", "PH", 1),
    ("로크웰오토메이션", "Rockwell Automation", "ROK", 1),
    ("도버", "Dover Corp", "DOV", 2),
    ("암텍", "AMETEK Inc", "AME", 1),
    ("포티브", "Fortive", "FTV", 2),
    ("UPS", "United Parcel Service", "UPS", 1),
    ("페덱스", "FedEx", "FDX", 1),
    ("3M", "3M Company", "MMM", 1),
    ("디어", "Deere & Company", "DE", 1),
    ("노스럽그루먼", "Northrop Grumman", "NOC", 1),
    ("제너럴다이나믹스", "General Dynamics", "GD", 1),
    ("L3해리스", "L3Harris Technologies", "LHX", 1),
    ("텍스트론", "Textron", "TXT", 2),
    ("트랜스다임", "TransDigm Group", "TDG", 1),
    ("롭스", "Roper Technologies", "ROP", 2),
    ("CSX", "CSX Corp", "CSX", 1),
    ("노포크서던", "Norfolk Southern", "NSC", 1),
    ("CPKC철도", "Canadian Pacific Kansas City", "CP", 2),
    ("올드도미니언", "Old Dominion Freight Line", "ODFL", 2),
    ("XPO", "XPO Inc", "XPO", 2),
    ("CH로빈슨", "C.H. Robinson", "CHRW", 2),
    ("엑스페다이터스", "Expeditors International", "EXPD", 2),
    ("JB헌트", "J.B. Hunt Transport", "JBHT", 2),
    ("랜드스타시스템", "Landstar System", "LSTR", 2),
    ("GXO로지스틱스", "GXO Logistics", "GXO", 2),
    ("사이아", "Saia Inc", "SAIA", 2),
    ("라이더시스템", "Ryder System", "R", 2),
    ("유나이티드렌탈스", "United Rentals", "URI", 1),
    ("GATX", "GATX Corp", "GATX", 3),
    ("에어리스항공", "Air Lease Corp", "AL", 2),
    ("사우스웨스트항공", "Southwest Airlines", "LUV", 2),
    ("아메리칸항공", "American Airlines", "AAL", 2),
    ("델타항공", "Delta Air Lines", "DAL", 1),
    ("유나이티드항공", "United Airlines", "UAL", 1),
    ("웨이스트매니지먼트", "Waste Management", "WM", 1),
    ("리퍼블릭서비스", "Republic Services", "RSG", 1),
    ("파카플루이드", "Parker Hannifin", "PH", 1),
    ("미드컨티넨트", "Middleby Corp", "MIDD", 2),
    ("IDEX", "IDEX Corp", "IEX", 2),
    ("신시내티공작기계", "Cincinnati Financial", "CINF", 2),
    ("그라코", "Graco Inc", "GGG", 2),
    ("노드슨", "Nordson Corp", "NDSN", 2),
    # ── 에너지 ────────────────────────────────────────────
    ("엑슨모빌", "ExxonMobil", "XOM", 1),
    ("셰브론", "Chevron", "CVX", 1),
    ("코노코필립스", "ConocoPhillips", "COP", 1),
    ("슐럼버거SLB", "SLB Schlumberger", "SLB", 1),
    ("EOG리소시스", "EOG Resources", "EOG", 1),
    ("마라톤페트롤리엄", "Marathon Petroleum", "MPC", 1),
    ("발레로에너지", "Valero Energy", "VLO", 1),
    ("필립스66", "Phillips 66", "PSX", 1),
    ("옥시덴털", "Occidental Petroleum", "OXY", 1),
    ("할리버튼", "Halliburton", "HAL", 2),
    ("베이커휴즈", "Baker Hughes", "BKR", 2),
    ("킨더모건", "Kinder Morgan", "KMI", 2),
    ("윌리엄스컴퍼니", "Williams Companies", "WMB", 2),
    ("원오케이", "ONEOK", "OKE", 2),
    ("셰니에르에너지", "Cheniere Energy", "LNG", 1),
    ("데본에너지", "Devon Energy", "DVN", 2),
    ("다이아몬드백에너지", "Diamondback Energy", "FANG", 2),
    ("헤스", "Hess Corp", "HES", 2),
    ("마라톤오일", "Marathon Oil", "MRO", 2),
    ("APA코프", "APA Corp", "APA", 2),
    ("EQT", "EQT Corp", "EQT", 2),
    ("안테로리소스", "Antero Resources", "AR", 3),
    ("SM에너지", "SM Energy", "SM", 3),
    ("레인지리소스", "Range Resources", "RRC", 3),
    ("마테더오일앤드가스", "Matador Resources", "MTDR", 3),
    ("코테라에너지", "Coterra Energy", "CTRA", 2),
    # ── 소재 ──────────────────────────────────────────────
    ("린데", "Linde plc", "LIN", 1),
    ("에어프로덕츠", "Air Products & Chemicals", "APD", 1),
    ("셔윈윌리엄스", "Sherwin-Williams", "SHW", 1),
    ("에코랩", "Ecolab", "ECL", 1),
    ("뉴몬트", "Newmont Corp", "NEM", 1),
    ("프리포트맥모런", "Freeport-McMoRan", "FCX", 1),
    ("뉴코어", "Nucor Corp", "NUE", 2),
    ("스틸다이나믹스", "Steel Dynamics", "STLD", 2),
    ("릴라이언스스틸", "Reliance Steel", "RS", 2),
    ("셀라니스", "Celanese", "CE", 2),
    ("이스트만케미칼", "Eastman Chemical", "EMN", 2),
    ("RPM인터내셔널", "RPM International", "RPM", 2),
    ("PPG", "PPG Industries", "PPG", 1),
    ("다우", "Dow Inc", "DOW", 1),
    ("라이온델바셀", "LyondellBasell", "LYB", 1),
    ("헌츠만", "Huntsman Corp", "HUN", 2),
    ("올린", "Olin Corp", "OLN", 2),
    ("소노코제품", "Sonoco Products", "SON", 2),
    ("실드에어", "Sealed Air", "SEE", 2),
    ("에이버리데니슨", "Avery Dennison", "AVY", 2),
    ("볼메탈", "Ball Corp", "BALL", 2),
    ("인터내셔널페이퍼", "International Paper", "IP", 2),
    ("웨스트록", "WestRock", "WRK", 2),
    ("실건메탈", "Silgan Holdings", "SLGN", 3),
    ("패키징코프", "Packaging Corp of America", "PKG", 2),
    # ── 부동산·리츠 ───────────────────────────────────────
    ("아메리칸타워", "American Tower", "AMT", 1),
    ("프롤로지스", "Prologis", "PLD", 1),
    ("에퀴닉스", "Equinix", "EQIX", 1),
    ("사이먼프로퍼티", "Simon Property Group", "SPG", 1),
    ("퍼블릭스토리지", "Public Storage", "PSA", 1),
    ("웰타워", "Welltower", "WELL", 1),
    ("디지털리얼티", "Digital Realty", "DLR", 1),
    ("크라운캐슬", "Crown Castle", "CCI", 1),
    ("엑스트라스페이스", "Extra Space Storage", "EXR", 1),
    ("에반스베이", "Equity Residential", "EQR", 2),
    ("어반에지", "AvalonBay Communities", "AVB", 2),
    ("미드아메리카아파트", "Mid-America Apartment", "MAA", 2),
    ("캠든프로퍼티", "Camden Property Trust", "CPT", 2),
    ("호스트호텔", "Host Hotels & Resorts", "HST", 2),
    ("SL그린", "SL Green Realty", "SLG", 3),
    ("보스턴프로퍼티", "Boston Properties", "BXP", 2),
    ("레가시호스팅", "Regency Centers", "REG", 2),
    ("페더럴리얼티", "Federal Realty Investment", "FRT", 2),
    ("킴코리얼티", "Kimco Realty", "KRG", 3),
    ("UDR", "UDR Inc", "UDR", 2),
    ("에섹스프로퍼티", "Essex Property Trust", "ESS", 2),
    ("인비테이션홈즈", "Invitation Homes", "INVH", 2),
    ("아메리칸홈즈포렌트", "American Homes 4 Rent", "AMH", 2),
    ("내셔널리테일", "NNN REIT", "NNN", 2),
    ("WP캐리", "W. P. Carey", "WPC", 2),
    ("리얼티인컴", "Realty Income", "O", 1),
    ("VICI프로퍼티", "VICI Properties", "VICI", 2),
    ("CBRE그룹", "CBRE Group", "CBRE", 1),
    ("존스랭라살", "Jones Lang LaSalle", "JLL", 2),
    ("쿠시먼앤드웨이크필드", "Cushman & Wakefield", "CWK", 3),
    # ── 유틸리티 ──────────────────────────────────────────
    ("넥스테라에너지", "NextEra Energy", "NEE", 1),
    ("서던컴퍼니", "Southern Company", "SO", 1),
    ("듀크에너지", "Duke Energy", "DUK", 1),
    ("아메리칸일렉트릭파워", "American Electric Power", "AEP", 1),
    ("엑셀론", "Exelon Corp", "EXC", 1),
    ("엑셀에너지", "Xcel Energy", "XEL", 2),
    ("셈프라에너지", "Sempra Energy", "SRE", 1),
    ("PG&E", "Pacific Gas & Electric", "PCG", 2),
    ("콘에디슨", "Consolidated Edison", "ED", 2),
    ("WEC에너지", "WEC Energy Group", "WEC", 2),
    ("에버소스에너지", "Eversource Energy", "ES", 2),
    ("아메리칸워터웍스", "American Water Works", "AWK", 2),
    ("엔터지", "Entergy Corp", "ETR", 2),
    ("퍼스트에너지", "FirstEnergy Corp", "FE", 2),
    ("PPL코프", "PPL Corp", "PPL", 2),
    ("센터포인트에너지", "CenterPoint Energy", "CNP", 2),
    ("니소스에너지", "NiSource", "NI", 2),
    ("앨라이언트에너지", "Alliant Energy", "LNT", 2),
    ("피나클웨스트캐피탈", "Pinnacle West Capital", "PNW", 2),
    ("에버지", "Evergy", "EVRG", 2),
    ("AES코프", "AES Corp", "AES", 2),
    ("NRG에너지", "NRG Energy", "NRG", 2),
    ("CMS에너지", "CMS Energy", "CMS", 2),
    ("아이다코프", "IDACORP", "IDA", 3),
    ("블랙힐스", "Black Hills Corp", "BKH", 3),
    ("엘파소일렉트릭", "El Paso Electric", "EE", 3),
    ("오터테일", "Otter Tail Corp", "OTTR", 3),
]

def _merge_universe(base: list) -> list:
    """universe.py의 전 종목을 검색 DB에 자동 합침 — 누락 종목도 검색되게.
    search_db에 이미 있으면 그대로 두고, 없으면 universe의 한글명으로 추가."""
    have = {t for _, _, t, _ in base}
    merged = list(base)
    try:
        from universe import KR_UNIVERSE, US_UNIVERSE
        for uni in (KR_UNIVERSE, US_UNIVERSE):
            for _sector, items in uni.items():
                for tk, name in items:
                    if tk not in have:
                        merged.append((name, name, tk, 4))  # tier 4 = 보조
                        have.add(tk)
    except Exception:
        pass
    return merged


ALL_STOCKS = _merge_universe(KR_STOCKS + US_STOCKS)


def search(query: str, max_results: int = 10) -> list[dict]:
    """
    회사명(한글·영문) 부분 일치 검색.
    시총 tier 오름차순(대형주 우선)으로 정렬해서 반환.
    """
    if not query or len(query.strip()) < 1:
        return []

    q = query.strip().lower()
    results = []
    seen = set()

    for kor, eng, ticker, tier in ALL_STOCKS:
        if ticker in seen:
            continue
        if q in kor.lower() or q in eng.lower() or q in ticker.lower():
            results.append({
                "kor": kor,
                "eng": eng,
                "ticker": ticker,
                "tier": tier,
                "display": f"{kor} ({ticker})",
                "label": f"{kor}  ·  {eng}  [{ticker}]",
            })
            seen.add(ticker)

    results.sort(key=lambda x: x["tier"])
    return results[:max_results]
